site_name: NightDrive
site_url: https://woulfdev.github.io/nightdrive/
site_author: Elia
site_description: >-
  Documentation about NightDrive API and Mobile App.

repo_name: NightDrive
repo_url: https://github.com/woulfdev/nightdrive

edit_uri: edit/main/docs/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/woulfdev    

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  langauge: en
  name: material
  features:
    - content.action.view
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - search.suggest
    - content.tooltips
  icon: 
    repo: fontawesome/brands/github
    annotation: material/circle-medium
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Features:
    - Drives: drives.md
  - Deployment: 
    - deploy.md
    - Variables: env-variables.md
  - App: app/index.md