site_name: NightDrive
site_url: https://nightdrive.dev
site_author: Elia
site_description: >-
  Self hosted solution for tracking, categorizing and sharing drives from your car or motorcycle.

repo_name: NightDrive
repo_url: https://github.com/woulfdev/nightdrive

edit_uri: edit/main/docs/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/woulfdev

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  # - git-committers:
      # repository: woulfdev/nightdrive
      # branch: main
  - privacy

markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  # - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

theme:
  langauge: en
  name: material
  custom_dir: overrides
  features:
    - content.action.view
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tooltips
  icon: 
    repo: fontawesome/brands/github
    annotation: material/circle-medium
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: nightdrive
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

not_in_nav: 
  license.md

nav:
  - Home: index.md
  - Features:
    - Drives: features/drives.md
  - Deployment: 
    - deployment/index.md
    - Installation:
      - deployment/instal/docker.md
    - Variables: deployment/env-variables.md
  - API Referece:
    - api/index.md
  - App: app/index.md